// Generated by CoffeeScript 1.6.3
(function() {
  var Model;

  Model = (function() {
    function Model(spec) {
      if (spec == null) {
        spec = "L";
      }
      this.spec = ko.observable(spec);
    }

    return Model;

  })();

  window.Model = Model;

}).call(this);

/*
//@ sourceMappingURL=Model.map
*/
