// Generated by CoffeeScript 1.6.3
(function() {
  var View,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  View = (function() {
    function View(model, id) {
      this.model = model;
      this._loop = __bind(this._loop, this);
      this._setup(id);
    }

    View.prototype._setup = function(id) {
      var canvas, composite, dpr, height, particle, width;
      canvas = document.getElementById(id);
      width = parseInt(canvas.style.width);
      height = parseInt(canvas.style.height);
      dpr = window.devicePixelRatio || 1;
      canvas.width = width * dpr;
      canvas.height = height * dpr;
      canvas.getContext("2d").scale(dpr, dpr);
      this.sim = new VerletJS(width, height, canvas);
      this.sim.friction = 0.3;
      this.origin = new Vec2(width / 2, 3 * height / 4);
      composite = new VerletJS.Composite();
      particle = new Particle(this.origin);
      composite.particles.push(particle);
      this.sim.composites.push(composite);
      return this._loop();
    };

    View.prototype._loop = function() {
      this.sim.frame(16);
      this.sim.draw();
      return window.requestAnimFrame(this._loop);
    };

    return View;

  })();

  window.View = View;

}).call(this);

/*
//@ sourceMappingURL=View.map
*/
