// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  describe('InstructionVisitor', function() {
    return describe('basic', function() {
      var origin;
      origin = new Vec2(0.0, 0.0);
      return describe('visitForward', function() {
        return it('forward moves one unit in default direction', function() {
          var parent, visitor;
          parent = new Root(origin);
          assert.isNull(parent.nextLink);
          visitor = new InstructionVisitor(origin, parent);
          visitor.visitForward('name', 'blue', 1.0);
          assert.isNotNull(parent.nextLink);
          assert.equal(parent.nextLink.startParticle.pos.x, origin.x);
          assert.equal(parent.nextLink.startParticle.pos.y, origin.y);
          assert.equal(parent.nextLink.endParticle().pos.x, origin.x);
          return assert.equal(parent.nextLink.endParticle().pos.y, origin.y - 20.0);
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=InstructionVisitor.spec.map
*/
