// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  describe('InstructionVisitor', function() {
    return describe('basic', function() {
      var origin;
      origin = new Vec2(0.0, -1.0);
      return describe('visitForward', function() {
        return it('single forward moves one unit in default direction', function() {
          var parent, visitor;
          parent = new Root(origin);
          visitor = new InstructionVisitor(origin, parent);
          return assert.equal(false, true, "to be completed");
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=InstructionVisitor.spec.map
*/
