// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  describe('Node', function() {
    var nextUntilEnd;
    nextUntilEnd = function(iter) {
      var names;
      names = [];
      names.push(iter.node.name);
      while (iter.hasNext()) {
        iter.next();
        names.push(iter.node.name);
      }
      return names;
    };
    return describe('read-only iteration', function() {
      it('single node', function() {
        var names, tree;
        tree = new Node("A");
        names = nextUntilEnd(tree.iterator());
        return assert.deepEqual(names, ["A"]);
      });
      return it('non-empty, multi-level', function() {
        var names, tree;
        tree = new Node("A", new Node("B", new Node("A")));
        names = nextUntilEnd(tree.iterator());
        return assert.deepEqual(names, ["A", "B", "A"]);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=Node.spec.map
*/
