apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lsystemsed
  namespace: lsystemsed
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: lsystemsed
  template:
    metadata:
      labels:
        app: lsystemsed
    spec:
      containers:
        - name: lsystemsed
          image: houseofmoran/lsystemsed:0.6.1_2
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 500Mi
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 120
            timeoutSeconds: 1
