// Generated by CoffeeScript 1.6.3
(function() {
  var Element,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Element = (function() {
    function Element(composite) {
      this.composite = composite != null ? composite : null;
      this._drawParticles = __bind(this._drawParticles, this);
      this._addParticle = __bind(this._addParticle, this);
    }

    Element.prototype._addParticle = function(particle) {
      console.log("add");
      console.dir(particle);
      if (this.composite == null) {
        this.composite = new VerletJS.Composite();
        this.composite.drawParticles = this._drawParticles;
      }
      return this.composite.particles.push(particle);
    };

    Element.prototype._drawParticles = function(ctx, composite) {
      var end, particle, start, _i, _len, _ref, _results;
      _ref = composite.particles;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        particle = _ref[_i];
        if (particle.link != null) {
          start = particle.link.startParticle;
          end = particle;
          ctx.beginPath();
          ctx.arc(end.pos.x, end.pos.y, 2, 0, 2 * Math.PI);
          ctx.fillStyle = particle.link.color;
          ctx.fill();
          ctx.beginPath();
          ctx.moveTo(start.pos.x, start.pos.y);
          ctx.lineTo(end.pos.x, end.pos.y);
          ctx.strokeStyle = "gray";
          _results.push(ctx.stroke());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Element;

  })();

  window.Element = Element;

}).call(this);

/*
//@ sourceMappingURL=Element.map
*/
