// Generated by CoffeeScript 1.6.3
(function() {
  var InstructionVisitor,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  InstructionVisitor = (function() {
    function InstructionVisitor(origin, parent) {
      this.origin = origin;
      this.parent = parent;
      this.visitNested = __bind(this.visitNested, this);
      this._drawParticles = __bind(this._drawParticles, this);
      this._addParticle = __bind(this._addParticle, this);
      this.visitForward = __bind(this.visitForward, this);
      this.direction = new Vec2(0.0, -1.0);
      this.stride = 20.0;
      this.composite = null;
      if (this.parent.nextLink != null) {
        this.parent.nextLink.markDead();
      }
    }

    InstructionVisitor.prototype.visitForward = function(name, color, extent) {
      var link;
      if ((this.parent.nextLink != null) && this.parent.nextLink.name === name) {
        this.parent.nextLink.dead = false;
        return this.parent = this.parent.nextLink;
      } else {
        link = new Link(name, color, this.parent, this.parent.endParticle(), extent * this.stride, this.direction);
        this.parent.nextLink = link;
        this.parent = link;
        return this._addParticle(link.endParticle());
      }
    };

    InstructionVisitor.prototype._addParticle = function(particle) {
      console.log("add");
      console.dir(particle);
      if (this.composite == null) {
        this.composite = new VerletJS.Composite();
        this.composite.drawParticles = this._drawParticles;
      }
      return this.composite.particles.push(particle);
    };

    InstructionVisitor.prototype._drawParticles = function(ctx, composite) {
      var end, particle, start, _i, _len, _ref, _results;
      _ref = composite.particles;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        particle = _ref[_i];
        if (particle.link != null) {
          start = particle.link.startParticle;
          end = particle;
          ctx.beginPath();
          ctx.arc(end.pos.x, end.pos.y, 2, 0, 2 * Math.PI);
          ctx.fillStyle = particle.link.color;
          ctx.fill();
          ctx.beginPath();
          ctx.moveTo(start.pos.x, start.pos.y);
          ctx.lineTo(end.pos.x, end.pos.y);
          ctx.strokeStyle = "gray";
          _results.push(ctx.stroke());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    InstructionVisitor.prototype.visitNested = function(nested) {
      var instruction, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = nested.length; _i < _len; _i++) {
        instruction = nested[_i];
        _results.push(instruction.accept(this));
      }
      return _results;
    };

    return InstructionVisitor;

  })();

  window.InstructionVisitor = InstructionVisitor;

}).call(this);

/*
//@ sourceMappingURL=InstructionVisitor.map
*/
