// Generated by CoffeeScript 1.6.3
(function() {
  var Link,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Link = (function() {
    function Link(name, color, parent, startParticle, extent, direction) {
      this.name = name;
      this.color = color;
      this.parent = parent;
      this.startParticle = startParticle;
      this.extent = extent;
      this.direction = direction;
      this.unlink = __bind(this.unlink, this);
      this.markDead = __bind(this.markDead, this);
      this.endParticle = __bind(this.endParticle, this);
      this.end = new Particle(this.startParticle.pos.add(this.direction.scale(this.extent)));
      this.end.link = this;
      this.dead = false;
      this.nextLink = null;
    }

    Link.prototype.endParticle = function() {
      return this.end;
    };

    Link.prototype.markDead = function() {
      if (this.nextLink != null) {
        this.nextLink.markDead();
      }
      return this.dead = true;
    };

    Link.prototype.unlink = function() {
      return this.parent.nextLink = this.nextLink;
    };

    return Link;

  })();

  window.Link = Link;

}).call(this);

/*
//@ sourceMappingURL=Link.map
*/
