// Generated by CoffeeScript 1.6.3
(function() {
  var NodeSynchronizer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  NodeSynchronizer = (function() {
    function NodeSynchronizer() {
      this.syncUp = __bind(this.syncUp, this);
    }

    NodeSynchronizer.prototype.syncUp = function(destIter, srcIter) {
      if (srcIter.node.name !== destIter.node.name) {
        destIter.replaceWith(srcIter.node);
        if (destIter.hasNext()) {
          return this.syncUp(destIter.next(), srcIter.next());
        }
      } else {
        if (srcIter.hasNext()) {
          if (destIter.hasNext()) {
            return this.syncUp(destIter.next(), srcIter.next());
          } else {
            destIter.append(srcIter.node.next);
            return this.syncUp(destIter.next(), srcIter.next());
          }
        } else {
          if (destIter.hasNext()) {
            return destIter.cut();
          } else {

          }
        }
      }
    };

    return NodeSynchronizer;

  })();

  window.NodeSynchronizer = NodeSynchronizer;

}).call(this);

/*
//@ sourceMappingURL=NodeSynchronizer.map
*/
