// Generated by CoffeeScript 1.6.3
(function() {
  var DepthFirstIterator, Node,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DepthFirstIterator = (function() {
    function DepthFirstIterator(node) {
      this.node = node;
      this._findNextNode = __bind(this._findNextNode, this);
      this.cut = __bind(this.cut, this);
      this.append = __bind(this.append, this);
      this.replaceWith = __bind(this.replaceWith, this);
      this.next = __bind(this.next, this);
      this.hasNext = __bind(this.hasNext, this);
      this.stack = [];
    }

    DepthFirstIterator.prototype.hasNext = function() {
      this._findNextNode();
      return this.stack.length > 0;
    };

    DepthFirstIterator.prototype.next = function() {
      if (!this.hasNext()) {
        throw new Error("no next node");
      }
      this.node = this.stack.pop();
      return this;
    };

    DepthFirstIterator.prototype.replaceWith = function(newNode) {
      this.node.name = newNode.name;
      this.node.next = newNode.next;
      return this;
    };

    DepthFirstIterator.prototype.append = function(newNext) {
      if (this.node.next != null) {
        throw new Error("illegal operation");
      }
      return this.node.next = newNext;
    };

    DepthFirstIterator.prototype.cut = function() {
      return this.node.next = null;
    };

    DepthFirstIterator.prototype._findNextNode = function() {
      if (this.stack.length === 0) {
        if (this.node.next != null) {
          return this.stack.push(this.node.next);
        }
      }
    };

    return DepthFirstIterator;

  })();

  Node = (function() {
    function Node(name, next) {
      this.name = name;
      this.next = next;
      this.iterator = __bind(this.iterator, this);
    }

    Node.prototype.iterator = function() {
      return new DepthFirstIterator(this);
    };

    return Node;

  })();

  window.Node = Node;

}).call(this);

/*
//@ sourceMappingURL=Node.map
*/
