// Generated by CoffeeScript 1.6.3
(function() {
  var Area, Link, Pen,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Area = (function() {
    function Area() {
      this._drawParticles = __bind(this._drawParticles, this);
      this.addEndpointAt = __bind(this.addEndpointAt, this);
      this.composite = null;
    }

    Area.prototype.addEndpointAt = function(position, link) {
      var particle;
      particle = new Particle(position);
      particle.link = link;
      if (this.composite == null) {
        this.composite = new VerletJS.Composite();
        this.composite.drawParticles = this._drawParticles;
      }
      return this.composite.particles.push(particle);
    };

    Area.prototype._drawParticles = function(ctx, composite) {
      var end, particle, start, _i, _len, _ref, _results;
      _ref = composite.particles;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        particle = _ref[_i];
        if (particle.link != null) {
          start = particle.link.startParticle;
          end = particle;
          ctx.beginPath();
          ctx.arc(end.pos.x, end.pos.y, 2, 0, 2 * Math.PI);
          ctx.fillStyle = particle.link.color;
          ctx.fill();
          ctx.beginPath();
          ctx.moveTo(start.pos.x, start.pos.y);
          ctx.lineTo(end.pos.x, end.pos.y);
          ctx.strokeStyle = "gray";
          _results.push(ctx.stroke());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Area;

  })();

  Link = (function() {
    function Link() {}

    return Link;

  })();

  Pen = (function() {
    function Pen(origin) {
      this.drawLink = __bind(this.drawLink, this);
      this.curr = new Link(origin);
      this.root = this.curr;
      this.direction = new Vec2(0.0, -1.0);
      this.stride = 20.0;
      this.area = new Area();
    }

    Pen.prototype.drawLink = function(name, extent) {};

    return Pen;

  })();

  window.Pen = Pen;

}).call(this);

/*
//@ sourceMappingURL=Pen.map
*/
