// Generated by CoffeeScript 1.6.3
(function() {
  var Root,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Root = (function() {
    function Root(origin, nextLink) {
      this.origin = origin;
      this.nextLink = nextLink != null ? nextLink : null;
      this.endParticle = __bind(this.endParticle, this);
      this.end = new Particle(this.origin);
    }

    Root.prototype.endParticle = function() {
      return this.end;
    };

    return Root;

  })();

  window.Root = Root;

}).call(this);

/*
//@ sourceMappingURL=Root.map
*/
